export { default as HomePage } from "./homepage/HomePage"
export { default as LoginPage } from "./loginpage/LoginPage"
export { default as RegisterPage } from "./registerpage/RegisterPage"
export { default as ForgotPasswordPage } from "./forgotpasswordpage/ForgotPasswordPage"
export { default as GroupsViewPage } from "./groupsviewpage/GroupsViewPage"
export { default as ProfilePage } from "./profilepage/ProfilePage"
export { default as GroupPage} from "./grouppage/GroupPage"
export { default as CreateGroupPage } from "./creategrouppage/CreateGroupPage"
export { default as DashboardHomePage } from "./dashboardhome/DashboardHome"
export { default as TextsViewPage } from "./textsviewpage/TextsViewPage"
export { default as TextViewPage } from "./textviewpage/TextViewPage"
export { default as AssignmentPage } from "./assignmentpage/AssignmentPage"
export { default as SubmitTextPage } from "./submittextpage/SubmitTextPage"
export { default as SubmittmentPage } from "./submittmentpage/SubmittmentPage"